---
- name: Set timezone using timedatectl
  command: timedatectl set-timezone "{{ timezone }}"

- name: Enable and start chrony or systemd-timesyncd (try chrony first)
  block:
    - name: Install chrony
      apt:
        name: chrony
        state: present
    - name: Ensure chrony enabled and started
      service:
        name: chrony
        state: started
        enabled: yes
  rescue:
    - name: Fallback to systemd-timesyncd (Debian)
      service:
        name: systemd-timesyncd
        state: started
        enabled: yes
