---
- name: Install prerequisites
  apt:
    name: apt-transport-https
    state: present

- name: Add Grafana APT key and repo
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repo
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present

- name: Install grafana
  apt:
    name: "{{ grafana_package }}"
    state: present
    update_cache: yes

- name: Ensure grafana enabled and started
  service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: yes

- name: Wait for grafana to be up (port checking)
  wait_for:
    host: 127.0.0.1
    port: 3000
    timeout: 30
