---
- name: Infra setup
  hosts: all
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/prometheus.yml
    - group_vars/node-exporter.yml
    - group_vars/grafana.yml
    - group_vars/nginx.yml

  pre_tasks:
    - name: Ensure apt cache updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: Run default_common role
      include_role:
        name: default-common
      when: '"default-common" in roles_to_run'

    - name: Run timedatectl role
      include_role:
        name: timedatectl
      when: '"timedatectl" in roles_to_run'

    - name: Run prometheus role
      include_role:
        name: prometheus
      when: '"prometheus" in roles_to_run'

    - name: Run node_exporter role
      include_role:
        name: node-exporter
      when: '"node-exporter" in roles_to_run'

    - name: Run grafana role
      include_role:
        name: grafana
      when: '"grafana" in roles_to_run'

    - name: Run nginx role
      include_role:
        name: nginx
      when: '"nginx" in roles_to_run'

  handlers:
    - name: restart prometheus
      systemd:
        name: "{{ prometheus_service_name }}"
        state: restarted
    - name: restart node-exporter
      systemd:
        name: "{{ node_exporter_service_name }}"
        state: restarted
    - name: restart nginx
      service:
        name: nginx
        state: restarted
